sonar.projectKey=ngodoanquang98_sample_app
sonar.organization=ngodoanquang98

sonar.projectName=sample_app
sonar.sourceEncoding=UTF-8

sonar.sources=.

sonar.exclusions=\
  **/vendor/**,\
  **/tmp/**,\
  **/log/**,\
  **/public/assets/**,\
  **/node_modules/**,\
  **/.git/**,\
  **/coverage/**